- name: install Docker
  import_tasks: install_docker.yml

- name: install docker-compose
  import_tasks: install_compose.yml

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Secure Docker Configuration - Disable Root Access
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "no-new-privileges": true,
        "userns-remap": "default"
      }
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker